[build]
# Railway will automatically detect Python and install requirements.txt
# No build command needed

[deploy]
# Command to start your FastAPI application
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/"
healthcheckTimeout = 100
restartPolicyType = "never"